title:               NieR Automata Theme
tagline:             'A NieR theme for Jekyll'
description:          'A unique theme that replicates the in-game menu from the critically acclaimed NieR: Automata'
domain:               'ehrenamt.github.io'
url:                 'https://ehrenamt.github.io'
baseurl:             '/nier-automata-jekyll-theme/'
exclude:
  - README.md

permalink: pretty

plugins:
    - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  pages:
      output: true
      permalink: /:path
  intel:
    output: true
  
sass:
  style: compressed

kramdown:
  auto_ids: true
  input: GFM
